# create your drupal and postgres config here, based off the last assignment
version: '2'


services:
  custom-drupal:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: pwd123
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
